modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
showAsResourcePack = false

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
credits = "Eastonium147- Mod-Maker; DualM- Former Mod-Maker; TFGalvatron- Ideas/Textures; bijutdo- Textures; John_the_Late- Visionary Mastermind"

[[dependencies.nuicraft]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.nuicraft]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.nuicraft]]
modId = "azurelib"
type = "required"
versionRange = "[3.0,)"
ordering = "BEFORE"
side = "CLIENT"
